import { StyleSheet } from 'react-native';
import { colors, fonts, sizes } from '../design/theme';

export const cameraScreenStyles = StyleSheet.create({
    preparoContainer: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 24,
        gap: 16,
    },
    preparoTitulo: {
        fontFamily: fonts.monoSemi,
        fontSize: sizes.xl,
        color: colors.white,
        textAlign: 'center',
    },
    preparoSubtitulo: {
        fontFamily: fonts.body,
        fontSize: sizes.body,
        color: 'rgba(255,255,255,0.8)',
        textAlign: 'center',
    },
    instrucoesList: { width: '100%', gap: 10, marginTop: 8 },
    instrucaoItem: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 14,
        backgroundColor: 'rgba(255,255,255,0.12)',
        borderRadius: 16,
        padding: 14,
    },
    instrucaoIcone: {
        width: 40, height: 40, borderRadius: 20,
        backgroundColor: colors.creamLight,
        alignItems: 'center', justifyContent: 'center',
    },
    instrucaoTexto: { fontFamily: fonts.bodyMedium, fontSize: sizes.body, color: colors.white, flex: 1 },
    preparoBotao: { paddingHorizontal: 24, paddingBottom: 32 },
    cameraRoot: { flex: 1, backgroundColor: '#000' },
    cameraTopBar: { paddingHorizontal: 20, paddingTop: 52, paddingBottom: 12 },
    cameraInstrucao: {
        alignSelf: 'center',
        backgroundColor: 'rgba(0,0,0,0.55)',
        paddingHorizontal: 18,
        paddingVertical: 8,
        borderRadius: 20,
        marginBottom: 12,
    },
    cameraInstrucaoTexto: { fontFamily: fonts.bodySemi, fontSize: sizes.caption, color: colors.white },
    moldura: { flex: 1, marginHorizontal: 24, marginBottom: 16, borderRadius: 16 },
    canto: { position: 'absolute', width: 24, height: 24, borderColor: colors.white },
    cantoTL: { top: 14, left: 14, borderTopWidth: 3, borderLeftWidth: 3 },
    cantoTR: { top: 14, right: 14, borderTopWidth: 3, borderRightWidth: 3 },
    cantoBL: { bottom: 14, left: 14, borderBottomWidth: 3, borderLeftWidth: 3 },
    cantoBR: { bottom: 14, right: 14, borderBottomWidth: 3, borderRightWidth: 3 },
    shutterArea: { alignItems: 'center', paddingBottom: 36 },
    shutter: {
        width: 72, height: 72, borderRadius: 36,
        backgroundColor: colors.creamLight,
        borderWidth: 5,
        borderColor: 'rgba(255,255,255,0.45)',
    },
    previewContainer: { flex: 1, paddingHorizontal: 16, gap: 12 },
    previewTitulo: { fontFamily: fonts.monoSemi, fontSize: sizes.lg, color: colors.white, textAlign: 'center' },
    previewFoto: { flex: 1, borderRadius: 18 },
    previewBotoes: { flexDirection: 'row', gap: 10, paddingHorizontal: 16, paddingBottom: 32 },
    confirmacaoCentro: { flex: 1, alignItems: 'center', justifyContent: 'center' },
    selo: {
        width: 200, height: 200, borderRadius: 100,
        backgroundColor: colors.goldLight,
        alignItems: 'center', justifyContent: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 12 },
        shadowOpacity: 0.3,
        shadowRadius: 18,
        elevation: 12,
    },
    seloInterno: {
        width: 130, height: 130, borderRadius: 65,
        backgroundColor: colors.creamLight,
        alignItems: 'center', justifyContent: 'center',
    },
    confirmacaoCard: {
        backgroundColor: colors.creamLight,
        marginHorizontal: 22,
        padding: 22,
        borderRadius: 22,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 4,
    },
    confirmacaoTitulo: { fontFamily: fonts.monoSemi, fontSize: sizes.lg, color: colors.orangeMid, marginBottom: 8 },
    confirmacaoTexto: { fontFamily: fonts.body, fontSize: sizes.bodySm, color: colors.inkSoft, textAlign: 'center', lineHeight: 20 },
    confirmacaoBotao: { paddingHorizontal: 22, paddingBottom: 32, paddingTop: 16 },
});
