import { StyleSheet } from 'react-native';
import { colors, fonts, sizes } from '../design/theme';

export const detalheDocumentoStyles = StyleSheet.create({
    top: { paddingHorizontal: 22, alignItems: 'center', paddingTop: 4 },
    heroIconWrap: {
        padding: 10,
        borderRadius: 32,
        backgroundColor: 'rgba(255,255,255,0.18)',
        marginBottom: 12,
    },
    titulo: {
        fontFamily: fonts.displayBlack,
        fontSize: sizes.xl,
        color: colors.white,
        letterSpacing: 0.5,
    },
    subtitulo: {
        fontFamily: fonts.body,
        fontSize: sizes.caption,
        color: 'rgba(255,255,255,0.85)',
        marginTop: 4,
        textAlign: 'center',
    },
    statusCircle: {
        width: 120, height: 120, borderRadius: 60,
        alignItems: 'center', justifyContent: 'center',
        marginVertical: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.2,
        shadowRadius: 12,
        elevation: 6,
    },
    statusBig: { fontFamily: fonts.displayBlack, fontSize: sizes.lg, color: colors.white },
    statusSub: {
        fontFamily: fonts.bodyMedium,
        fontSize: sizes.tiny,
        color: colors.white,
        opacity: 0.95,
        marginTop: 4,
        letterSpacing: 0.5,
    },
    descricao: {
        fontFamily: fonts.body,
        fontSize: sizes.bodySm,
        color: 'rgba(255,255,255,0.9)',
        textAlign: 'center',
        paddingHorizontal: 12,
        lineHeight: 20,
    },
    validade: { fontFamily: fonts.bodyMedium, fontSize: sizes.caption, color: 'rgba(255,255,255,0.8)', marginTop: 8 },
    acoes: {
        paddingHorizontal: 16,
        paddingBottom: 24,
        paddingTop: 18,
        gap: 10,
        marginTop: 'auto' as const,
    },
    player: { position: 'absolute', bottom: 24, right: 24 },
    bannnerDep: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: 8,
        marginHorizontal: 16,
        marginBottom: 4,
        backgroundColor: colors.creamLight,
        borderRadius: 12,
        padding: 12,
        borderLeftWidth: 3,
        borderLeftColor: colors.orangeMid,
    },
    bannerDepTexto: {
        fontFamily: fonts.body,
        fontSize: sizes.bodySm,
        color: colors.ink,
        flex: 1,
        lineHeight: 20,
    },
    bannerDepLink: {
        fontFamily: fonts.bodyBold,
        color: colors.tealDark,
        textDecorationLine: 'underline' as const,
    },
    avisoFundo: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.65)',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 24,
    },
    avisoCard: {
        backgroundColor: colors.creamLight,
        borderRadius: 24,
        padding: 24,
        width: '100%',
        alignItems: 'center',
        gap: 14,
    },
    avisoIcone: {
        width: 60, height: 60, borderRadius: 30,
        backgroundColor: colors.orangeMid,
        alignItems: 'center', justifyContent: 'center',
    },
    avisoTitulo: {
        fontFamily: fonts.displayBlack,
        fontSize: sizes.md,
        color: colors.orangeDark,
        textAlign: 'center',
    },
    avisoTexto: {
        fontFamily: fonts.body,
        fontSize: sizes.bodySm,
        color: colors.inkSoft,
        textAlign: 'center',
        lineHeight: 20,
    },
    avisoDestaque: {
        fontFamily: fonts.bodyBold,
        color: colors.redDark,
    },
    avisoBtn: {
        width: '100%',
        backgroundColor: colors.tealDark,
        borderRadius: 30,
        paddingVertical: 14,
        alignItems: 'center',
    },
    avisoBtnTexto: {
        fontFamily: fonts.bodySemi,
        fontSize: sizes.body,
        color: colors.white,
    },
    avisoBtnVoltar: {
        paddingVertical: 10,
        alignItems: 'center',
    },
    avisoBtnVoltarTexto: {
        fontFamily: fonts.bodyMedium,
        fontSize: sizes.body,
        color: colors.inkMute,
    },
});
