import { StyleSheet } from 'react-native';
import { colors, fonts, sizes } from '../design/theme';

export const documentosTabStyles = StyleSheet.create({
    titulo: {
        fontFamily: fonts.monoSemi,
        fontSize: sizes.lg,
        color: colors.tealDark,
        paddingHorizontal: 20,
        paddingTop: 24,
        paddingBottom: 6,
    },
    subtitulo: {
        fontFamily: fonts.body,
        fontSize: sizes.bodySm,
        color: colors.inkSoft,
        paddingHorizontal: 20,
        lineHeight: 20,
        paddingBottom: 12,
    },
    lista: { paddingHorizontal: 16, gap: 12 },
    linha: {
        gap: 12,
        justifyContent: 'space-between',
    },
    card: {
        flex: 1,
        backgroundColor: colors.white,
        borderRadius: 24,
        padding: 16,
        minHeight: 252,
        shadowColor: colors.tealDark,
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.08,
        shadowRadius: 20,
        elevation: 3,
    },
    cardPressable: {
        flex: 1,
    },
    cardIconeWrap: {
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 22,
        minHeight: 124,
        paddingHorizontal: 12,
        paddingVertical: 18,
        marginBottom: 14,
    },
    itemTipo: {
        fontFamily: fonts.monoSemi,
        fontSize: sizes.md,
        color: colors.tealDark,
    },
    itemNome: {
        fontFamily: fonts.body,
        fontSize: sizes.caption,
        color: colors.inkSoft,
        lineHeight: 17,
        minHeight: 50,
        marginTop: 4,
    },
    statusRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        marginTop: 8,
    },
    statusDot: {
        width: 10,
        height: 10,
        borderRadius: 5,
    },
    itemStatus: { fontFamily: fonts.bodySemi, fontSize: sizes.caption, color: colors.inkMute },
    cardFooter: {
        marginTop: 'auto',
        paddingTop: 14,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    abrirTexto: {
        fontFamily: fonts.bodySemi,
        fontSize: sizes.caption,
        color: colors.tealDark,
    },
    botaoVer: {
        width: 34,
        height: 34,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: colors.tealDark,
        borderRadius: 17,
    },
    modalFundo: { flex: 1, backgroundColor: 'rgba(0,0,0,0.92)', justifyContent: 'center', alignItems: 'center' },
    modalFoto: { width: '90%', height: '80%' },
    modalFechar: { position: 'absolute', top: 48, right: 20 },
    player: { position: 'absolute', right: 24 },
});
