import { StyleSheet } from 'react-native';
import { colors, fonts, sizes } from '../design/theme';

export const notasStyles = StyleSheet.create({
    header: {
        paddingHorizontal: 20,
        paddingTop: 20,
        paddingBottom: 12,
    },
    titulo: {
        fontFamily: fonts.displayBlack,
        fontSize: sizes.lg,
        color: colors.tealDark,
    },
    subtitulo: {
        fontFamily: fonts.body,
        fontSize: sizes.bodySm,
        color: colors.inkSoft,
        marginTop: 2,
    },
    lista: {
        paddingHorizontal: 16,
        paddingTop: 4,
        gap: 10,
    },
    card: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.white,
        borderRadius: 18,
        padding: 14,
        gap: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.06,
        shadowRadius: 6,
        elevation: 2,
    },
    cardIcone: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: colors.creamDeep,
        alignItems: 'center',
        justifyContent: 'center',
    },
    cardInfo: { flex: 1 },
    cardLinhaTopo: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    cardComprador: {
        flex: 1,
        fontFamily: fonts.bodySemi,
        fontSize: sizes.body,
        color: colors.ink,
    },
    cardDescricao: {
        fontFamily: fonts.body,
        fontSize: sizes.caption,
        color: colors.inkMute,
        marginTop: 2,
    },
    cardRodape: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        marginTop: 6,
    },
    cardData: {
        fontFamily: fonts.body,
        fontSize: sizes.micro,
        color: colors.inkMute,
    },
    cardValor: {
        fontFamily: fonts.bodyBold,
        fontSize: sizes.bodySm,
        color: colors.tealDark,
    },
    badge: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 3,
        paddingHorizontal: 8,
        paddingVertical: 3,
        borderRadius: 10,
    },
    badgeEmitida: {
        backgroundColor: 'rgba(31,122,122,0.12)',
    },
    badgePendente: {
        backgroundColor: 'rgba(201,95,46,0.14)',
    },
    badgeTexto: {
        fontFamily: fonts.bodySemi,
        fontSize: sizes.tiny,
    },
    btnExcluir: {
        padding: 4,
    },
    vazio: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 40,
        gap: 12,
    },
    vazioIcone: {
        width: 100,
        height: 100,
        borderRadius: 50,
        backgroundColor: 'rgba(31,122,122,0.1)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    vazioTitulo: {
        fontFamily: fonts.displayBlack,
        fontSize: sizes.md,
        color: colors.tealDark,
    },
    vazioTexto: {
        fontFamily: fonts.body,
        fontSize: sizes.body,
        color: colors.inkMute,
        textAlign: 'center',
        lineHeight: 22,
    },
    rodapeEmitir: {
        position: 'absolute',
        left: 20,
        right: 20,
        gap: 8,
    },
    botaoEmitir: {
        minHeight: 56,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        backgroundColor: colors.tealDark,
        borderRadius: 30,
        paddingVertical: 14,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 6,
    },
    botaoEmitirDesabilitado: {
        backgroundColor: colors.greyLight,
        shadowOpacity: 0,
        elevation: 0,
    },
    botaoEmitirTexto: {
        fontFamily: fonts.bodySemi,
        fontSize: sizes.body,
        color: colors.white,
    },
    dicaCertificado: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        alignSelf: 'center',
        gap: 6,
        backgroundColor: 'rgba(232,117,60,0.14)',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 14,
    },
    dicaCertificadoTexto: {
        fontFamily: fonts.bodyMedium,
        fontSize: sizes.caption,
        color: colors.orangeDark,
    },

    certCard: {
        marginHorizontal: 16,
        marginTop: 4,
        marginBottom: 8,
        borderRadius: 18,
        padding: 14,
        gap: 12,
    },
    certCardPendente: {
        backgroundColor: 'rgba(232,117,60,0.12)',
        borderWidth: 1,
        borderColor: 'rgba(168,69,30,0.22)',
    },
    certCardAtivo: {
        backgroundColor: colors.white,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.06,
        shadowRadius: 6,
        elevation: 2,
    },
    certTopo: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    certIcone: {
        width: 44,
        height: 44,
        borderRadius: 22,
        alignItems: 'center',
        justifyContent: 'center',
    },
    certIconePendente: {
        backgroundColor: 'rgba(201,95,46,0.18)',
    },
    certIconeAtivo: {
        backgroundColor: 'rgba(31,122,122,0.12)',
    },
    certInfo: { flex: 1, gap: 2 },
    certTitulo: {
        fontFamily: fonts.bodySemi,
        fontSize: sizes.body,
    },
    certTexto: {
        fontFamily: fonts.body,
        fontSize: sizes.caption,
        color: colors.inkMute,
        lineHeight: 17,
    },
    certValidade: {
        fontFamily: fonts.bodyMedium,
        fontSize: sizes.micro,
        color: colors.inkSoft,
        marginTop: 1,
    },
    certBotao: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 6,
        minHeight: 56,
        backgroundColor: colors.orangeDark,
        borderRadius: 12,
        paddingVertical: 10,
    },
    certBotaoTexto: {
        fontFamily: fonts.bodySemi,
        fontSize: sizes.bodySm,
        color: colors.white,
    },
    certTrocar: {
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 10,
        backgroundColor: 'rgba(31,122,122,0.10)',
    },
    certTrocarTexto: {
        fontFamily: fonts.bodySemi,
        fontSize: sizes.caption,
        color: colors.tealMid,
    },
});
