import { StyleSheet } from 'react-native';
import { colors, fonts, sizes } from '../design/theme';

export const onboardingStyles = StyleSheet.create({
    centro: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 24,
        gap: 18,
    },
    titulo36: {
        fontFamily: fonts.displayBlack,
        fontSize: 36,
        color: colors.white,
        textAlign: 'center',
        lineHeight: 42,
        marginTop: 14,
    },
    corpoBranco: {
        fontFamily: fonts.body,
        color: colors.white,
        fontSize: sizes.bodySm,
        textAlign: 'center',
        lineHeight: 20,
        paddingHorizontal: 8,
    },
    rodape: {
        paddingHorizontal: 22,
        paddingBottom: 32,
    },
    botaoFull: { width: '100%' },
    lgpdContainer: {
        flex: 1,
        justifyContent: 'center',
        paddingHorizontal: 18,
        paddingBottom: 32,
    },
    lgpdCard: {
        backgroundColor: colors.creamLight,
        borderRadius: 26,
        padding: 24,
        gap: 14,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.15,
        shadowRadius: 12,
        elevation: 6,
    },
    lgpdIcone: {
        width: 56, height: 56, borderRadius: 28,
        backgroundColor: colors.goldMid,
        alignItems: 'center', justifyContent: 'center',
        alignSelf: 'center',
    },
    lgpdTitulo: {
        fontFamily: fonts.display,
        fontSize: sizes.md,
        color: colors.ink,
        fontWeight: '700',
        textAlign: 'center',
    },
    lgpdCorpo: {
        fontFamily: fonts.body,
        fontSize: sizes.micro,
        color: colors.inkSoft,
        textAlign: 'center',
        lineHeight: 18,
    },
    lgpdAcoes: { gap: 10, marginTop: 'auto' as const },
    perfilEspacador: { height: 50 },
    perfilCard: {
        flex: 1,
        backgroundColor: colors.creamLight,
        marginHorizontal: 18,
        marginBottom: 30,
        borderRadius: 30,
        paddingHorizontal: 22,
        paddingBottom: 22,
        paddingTop: 0,
        alignItems: 'center' as const,
    },
    perfilAvatar: {
        width: 110, height: 110, borderRadius: 55,
        backgroundColor: colors.creamLight,
        borderWidth: 6,
        borderColor: colors.goldMid,
        alignItems: 'center', justifyContent: 'center',
        marginTop: -55,
        marginBottom: 14,
    },
    perfilTitulo: {
        fontFamily: fonts.display,
        fontSize: sizes.md,
        color: colors.ink,
        fontWeight: '700',
        marginBottom: 12,
    },
    perfilInput: {
        width: '100%',
        backgroundColor: colors.creamDeep,
        borderRadius: 16,
        padding: 14,
        fontFamily: fonts.bodyMedium,
        fontSize: sizes.body,
        color: colors.ink,
        marginBottom: 8,
    },
    perfilInfo: { width: '100%', gap: 4 },
    perfilRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        paddingVertical: 10,
        borderBottomWidth: 1,
        borderBottomColor: colors.creamDeep,
    },
    perfilRowIcone: {
        width: 38, height: 38, borderRadius: 19,
        backgroundColor: colors.goldMid,
        alignItems: 'center', justifyContent: 'center',
    },
    perfilRowLabel: {
        fontFamily: fonts.bodyMedium,
        fontSize: sizes.bodySm,
        color: colors.ink,
    },
    perfilRowValor: {
        fontFamily: fonts.body,
        fontSize: sizes.tiny,
        color: colors.inkMute,
        marginTop: 2,
    },
    tourCentro: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 24,
        gap: 20,
    },
    tourTitulo: {
        fontFamily: fonts.displayBlack,
        fontSize: 28,
        color: colors.white,
        textAlign: 'center',
    },
    tourCorpo: {
        fontFamily: fonts.body,
        color: colors.white,
        fontSize: sizes.bodySm,
        textAlign: 'center',
        lineHeight: 20,
        paddingHorizontal: 14,
    },
    tourDots: { flexDirection: 'row', gap: 8 },
    tourDot: {
        width: 8, height: 8, borderRadius: 4,
        backgroundColor: 'rgba(255,255,255,0.4)',
    },
    tourDotAtivo: { width: 22, backgroundColor: colors.white },
    tourRodape: {
        flexDirection: 'row',
        paddingHorizontal: 22,
        paddingBottom: 32,
        gap: 10,
    },
    praticaHeader: {
        paddingHorizontal: 24,
        paddingTop: 8,
        paddingBottom: 8,
        alignItems: 'center',
    },
    praticaTitulo: {
        fontFamily: fonts.displayBlack,
        fontSize: 26,
        color: colors.tealDark,
    },
    praticaSub: {
        fontFamily: fonts.body,
        fontSize: sizes.micro,
        color: colors.inkMute,
        marginTop: 4,
    },
    praticaLista: {
        flex: 1,
        paddingHorizontal: 18,
        paddingTop: 16,
        gap: 14,
    },
    praticaCard: {
        backgroundColor: colors.creamLight,
        borderRadius: 24,
        padding: 16,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 14,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.08,
        shadowRadius: 8,
        elevation: 3,
    },
    praticaIcone: {
        width: 52, height: 52, borderRadius: 26,
        alignItems: 'center', justifyContent: 'center',
    },
    praticaCardTitulo: {
        fontFamily: fonts.display,
        fontSize: 16,
        fontWeight: '700',
        color: colors.ink,
    },
    praticaCardSub: {
        fontFamily: fonts.body,
        fontSize: sizes.micro,
        color: colors.inkMute,
        marginTop: 2,
        lineHeight: 16,
    },
});

export const onboardingIlStyles = StyleSheet.create({
    bemVindoWrap: {
        width: 200, height: 200,
        alignItems: 'center', justifyContent: 'center',
    },
    bemVindoCirculoGrande: {
        position: 'absolute',
        width: 180, height: 180, borderRadius: 90,
        backgroundColor: 'rgba(255,255,255,0.12)',
    },
    bemVindoCirculoPequeno: {
        position: 'absolute',
        width: 140, height: 140, borderRadius: 70,
        backgroundColor: 'rgba(255,255,255,0.08)',
    },
    bemVindoSol: { position: 'absolute', top: 10, right: 20 },
    bemVindoFolha: { position: 'absolute', bottom: 14, left: 20 },
    cena: { width: 200, height: 200, alignItems: 'center', justifyContent: 'center' },
    cenaCirculo: {
        width: 186, height: 186, borderRadius: 93,
        alignItems: 'center', justifyContent: 'center',
        overflow: 'hidden',
    },
    sol: { position: 'absolute', top: 12, right: 20 },
    casinha: { position: 'absolute', bottom: 24, right: 24 },
    colina: {
        position: 'absolute', bottom: 0,
        width: 220, height: 40, borderRadius: 60,
        backgroundColor: 'rgba(255,255,255,0.1)',
    },
    docsGrid: { alignItems: 'center', gap: 10, flexDirection: 'column' },
    docsLinha1: { flexDirection: 'row', gap: 10 },
    docsLinha2: { flexDirection: 'row', gap: 10 },
    docCirculo: {
        width: 56, height: 56, borderRadius: 28,
        alignItems: 'center', justifyContent: 'center',
        shadowColor: '#000', shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.2, shadowRadius: 6, elevation: 4,
    },
    docLabel: { fontFamily: fonts.bodySemi, fontSize: 9, color: colors.white, fontWeight: '700' },
    telefone: {
        width: 120, height: 190, borderRadius: 18,
        backgroundColor: '#1a1a1a', overflow: 'hidden',
        shadowColor: '#000', shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.35, shadowRadius: 12, elevation: 8,
    },
    telefoneNotch: {
        width: 40, height: 8, borderRadius: 4,
        backgroundColor: '#333', alignSelf: 'center',
        marginTop: 8, marginBottom: 4,
    },
    telaCamera: {
        flex: 1, margin: 6, borderRadius: 10,
        backgroundColor: '#2a2a2a',
        alignItems: 'center', justifyContent: 'center', overflow: 'hidden',
    },
    cantoGuia: { position: 'absolute', width: 14, height: 14, borderColor: 'rgba(255,255,255,0.8)' },
    docMock: { width: '70%', backgroundColor: colors.creamDeep, borderRadius: 4, padding: 6, gap: 4 },
    docLinha: { height: 3, backgroundColor: colors.goldDark, borderRadius: 2, opacity: 0.6 },
    shutterArea: { height: 28, alignItems: 'center', justifyContent: 'center' },
    shutterBtn: {
        width: 20, height: 20, borderRadius: 10,
        backgroundColor: colors.creamLight,
        borderWidth: 2, borderColor: 'rgba(255,255,255,0.4)',
    },
    notifTelefone: {
        width: 160, height: 190, borderRadius: 18,
        backgroundColor: colors.tealDark, padding: 10,
        shadowColor: '#000', shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.3, shadowRadius: 12, elevation: 8,
    },
    notifTela: { flex: 1, gap: 8 },
    notifCard: {
        backgroundColor: 'rgba(255,255,255,0.15)',
        borderRadius: 12, padding: 10,
        flexDirection: 'row', alignItems: 'center', gap: 8,
    },
    notifIconeWrap: {
        width: 32, height: 32, borderRadius: 8,
        backgroundColor: colors.orangeMid,
        alignItems: 'center', justifyContent: 'center',
    },
    notifTitulo: { fontFamily: fonts.bodySemi, fontSize: 8, color: colors.white },
    notifTexto: { fontFamily: fonts.body, fontSize: 7, color: 'rgba(255,255,255,0.8)', marginTop: 2 },
    calCard: {
        backgroundColor: 'rgba(255,255,255,0.12)',
        borderRadius: 12, padding: 10,
        alignItems: 'center', justifyContent: 'center', flex: 1,
    },
    calNum: { fontFamily: fonts.displayBlack, fontSize: 40, color: colors.goldLight, lineHeight: 44 },
    calLabel: { fontFamily: fonts.bodyMedium, fontSize: 10, color: 'rgba(255,255,255,0.7)' },
});
