import { StyleSheet } from 'react-native';
import { colors, fonts, sizes } from '../design/theme';

export const roadmapDetailStyles = StyleSheet.create({
    content: {
        paddingHorizontal: 24,
        paddingTop: 8,
        paddingBottom: 48,
    },
    audioWrap: {
        alignItems: 'center',
        marginTop: 4,
        marginBottom: 8,
    },
    titulo: {
        fontFamily: fonts.display,
        fontSize: sizes.xxl,
        color: colors.tealDark,
        fontWeight: '700',
        textAlign: 'center',
    },
    categoriaBadge: {
        alignSelf: 'center',
        backgroundColor: colors.tealDark,
        paddingHorizontal: 14,
        paddingVertical: 4,
        borderRadius: 999,
        marginTop: 10,
    },
    categoriaBadgeText: {
        fontFamily: fonts.body,
        fontSize: sizes.bodySm,
        color: colors.white,
        fontWeight: '700',
        letterSpacing: 0.5,
    },
    hero: {
        fontFamily: fonts.body,
        fontSize: sizes.md,
        color: colors.inkSoft,
        textAlign: 'center',
        marginTop: 14,
        marginBottom: 28,
        lineHeight: 24,
    },
    sectionCard: {
        backgroundColor: colors.white,
        borderRadius: 18,
        padding: 18,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: colors.creamDeep,
        flexDirection: 'row',
        gap: 14,
        shadowColor: colors.tealDark,
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.06,
        shadowRadius: 3,
        elevation: 1,
    },
    sectionIconWrap: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: colors.creamLight,
        alignItems: 'center',
        justifyContent: 'center',
        flexShrink: 0,
    },
    sectionTextWrap: {
        flex: 1,
    },
    sectionTitle: {
        fontFamily: fonts.display,
        fontSize: sizes.md,
        color: colors.tealDark,
        fontWeight: '700',
        marginBottom: 4,
    },
    sectionBody: {
        fontFamily: fonts.body,
        fontSize: sizes.body,
        color: colors.inkSoft,
        lineHeight: 22,
    },
    resumoCard: {
        backgroundColor: colors.tealDark,
        borderRadius: 22,
        padding: 22,
        marginTop: 18,
        marginBottom: 24,
        flexDirection: 'row',
        gap: 14,
        alignItems: 'center',
    },
    resumoIconWrap: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: colors.goldMid,
        alignItems: 'center',
        justifyContent: 'center',
        flexShrink: 0,
    },
    resumoText: {
        flex: 1,
        fontFamily: fonts.display,
        fontSize: sizes.md,
        color: colors.white,
        fontWeight: '700',
        lineHeight: 24,
    },
    botao: {
        marginTop: 4,
    },
    placeholder: {
        marginTop: 24,
        marginBottom: 24,
        padding: 28,
        borderRadius: 18,
        backgroundColor: colors.white,
        borderWidth: 1,
        borderColor: colors.creamDeep,
        alignItems: 'center',
    },
    placeholderText: {
        fontFamily: fonts.body,
        fontSize: sizes.body,
        color: colors.inkMute,
        textAlign: 'center',
    },
});
